language: python
python:
  - "2.7_with_system_site_packages"
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
install: true
# command to run tests
script: python program.py